version: '3.9'
name: sophia

services:
  postgres:
    image: postgres:16-alpine
    container_name: sophia_postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - storify_network

  backend:
    build: 
      context: ..
      dockerfile: ./deploy/Dockerfile.backend
      args:
        - APP_NAME=${APP_NAME}
    container_name: sophia_backend
    ports:
      - "8080:8080"
    environment:
      - APP_NAME=${APP_NAME}
    depends_on:
      - postgres
    networks:
      - storify_network

volumes:
  postgres_data:

networks:
  storify_network:
    driver: bridge