FROM golang:1.22 AS builder

ARG APP_NAME
ENV APP_NAME ${APP_NAME}

WORKDIR /app

COPY ../backend/go.mod ../backend/go.sum ./

RUN go mod download

COPY ../backend/ ./

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix nocgo ./cmd/${APP_NAME}/

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/${APP_NAME} .

EXPOSE 8080

CMD sh -c "./${APP_NAME}"